FROM --platform=linux/amd64 ubuntu:20.04

RUN apt update && apt-get install python3-pip -y

WORKDIR /app
COPY . .

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

CMD ["uwsgi", "uwsgi.ini"]
