version: "3.4"

services:
  app:
    build:
      context: .
      dockerfile: "Dockerfile.ubuntu"
    volumes:
      - ./:/app
    restart: unless-stopped
    command: ["python3", "app.py", "runserver"]
    env_file:
      - .env
    expose:
      - ${APP_PORT}
    depends_on:
      - db

  # Nginx service
  webserver:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - .docker/nginx.conf:/etc/nginx/conf.d/default.conf

  # Mongodb
  # db:
  #   image: bitnami/mongodb:4.4.10
  #   restart: unless-stopped
  #   environment:
  #     MONGODB_DATABASE: ${DB_NAME}
  #     MONGODB_ROOT_USER: ${DB_USERNAME}
  #     MONGODB_ROOT_PASSWORD: ${DB_PASSWORD}
  #   volumes:
  #     - .docker/data/mongo:/bitnami/mongodb

  # Postgres service
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - .docker/data/db:/var/lib/postgresql/data
