"""empty message

Revision ID: 26c57124eadc
Revises: f00f2e294dbb
Create Date: 2022-02-16 08:22:14.413902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c57124eadc'
down_revision = 'f00f2e294dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('audio_sample_speaker_id_fkey', 'audio_sample', type_='foreignkey')
    op.create_foreign_key(None, 'audio_sample', 'speaker', ['speaker_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('speaker_user_id_fkey', 'speaker', type_='foreignkey')
    op.create_foreign_key(None, 'speaker', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'speaker', type_='foreignkey')
    op.create_foreign_key('speaker_user_id_fkey', 'speaker', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'audio_sample', type_='foreignkey')
    op.create_foreign_key('audio_sample_speaker_id_fkey', 'audio_sample', 'speaker', ['speaker_id'], ['id'])
    # ### end Alembic commands ###
