"""empty message

Revision ID: 27f79bd9aa04
Revises: 6b552356dc7e
Create Date: 2022-06-21 05:28:53.503403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f79bd9aa04'
down_revision = '6b552356dc7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('result_path', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('record', 'result_path')
    # ### end Alembic commands ###
